/* The following code was generated by JFlex 1.4.1 on 3/31/08 11:39 PM */

/***** JFlex specification for Arc *****/

package com.bitbakery.plugin.arc.lexer;

import static com.bitbakery.plugin.arc.lexer.ArcTokenTypes.*;
import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;


/**
 * This class is a scanner generated by
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 3/31/08 11:39 PM from the specification file
 * <tt>src/com/bitbakery/plugin/arc/lexer/arc.flex</tt>
 */
public class _ArcLexer implements FlexLexer {
    /**
     * initial size of the lookahead buffer
     */
    private static final int ZZ_BUFFERSIZE = 16384;

    /**
     * lexical states
     */
    public static final int YYINITIAL = 0;

    /**
     * Translates characters to character classes
     */
    private static final String ZZ_CMAP_PACKED =
            "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\25\1\16\1\20" +
                    "\1\7\3\16\1\45\1\21\1\22\1\5\1\14\1\46\1\14\1\15" +
                    "\1\6\1\12\11\11\1\50\1\4\1\16\1\43\2\16\1\47\1\52" +
                    "\1\16\1\53\1\37\1\13\1\36\1\16\1\41\1\31\2\16\1\32" +
                    "\1\51\1\30\1\35\1\16\1\33\2\16\1\27\1\34\1\16\1\40" +
                    "\3\16\1\23\1\17\1\24\1\16\1\26\1\44\1\52\1\16\1\53" +
                    "\1\37\1\13\1\36\1\16\1\41\1\31\2\16\1\32\1\51\1\30" +
                    "\1\35\1\16\1\33\2\16\1\27\1\34\1\16\1\40\3\16\1\0" +
                    "\1\10\1\0\1\42\uff81\0";

    /**
     * Translates characters to character classes
     */
    private static final char[] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

    /**
     * Translates DFA states to action switch labels.
     */
    private static final int[] ZZ_ACTION = zzUnpackAction();

    private static final String ZZ_ACTION_PACKED_0 =
            "\1\1\1\2\3\3\3\1\1\4\1\1\1\5\1\6" +
                    "\1\7\1\10\1\11\1\12\1\3\1\13\7\1\1\14" +
                    "\1\15\1\16\1\17\1\20\1\21\1\1\2\0\2\22" +
                    "\1\1\1\0\4\4\2\6\1\0\1\1\1\23\2\1" +
                    "\1\24\1\1\1\25\1\1\1\26\1\1\1\0\2\1" +
                    "\1\27\1\30\1\31\1\32\1\1\1\33\1\1\1\34" +
                    "\2\0\1\35\1\1\1\36\1\35\1\37";

    private static int[] zzUnpackAction() {
        int[] result = new int[73];
        int offset = 0;
        offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAction(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }


    /**
     * Translates a state to a row index in the transition table
     */
    private static final int[] ZZ_ROWMAP = zzUnpackRowMap();

    private static final String ZZ_ROWMAP_PACKED_0 =
            "\0\0\0\54\0\130\0\54\0\204\0\260\0\334\0\u0108" +
                    "\0\u0134\0\u0160\0\u018c\0\u01b8\0\54\0\54\0\54\0\54" +
                    "\0\u01e4\0\334\0\u0210\0\u023c\0\u0268\0\u0294\0\u02c0\0\u02ec" +
                    "\0\u0318\0\54\0\334\0\54\0\54\0\u0344\0\54\0\u0370" +
                    "\0\204\0\u039c\0\u03c8\0\54\0\u03f4\0\u0420\0\u044c\0\u0478" +
                    "\0\u04a4\0\334\0\u04d0\0\54\0\u04fc\0\u0528\0\334\0\u0554" +
                    "\0\u0580\0\334\0\u05ac\0\334\0\u05d8\0\54\0\u0604\0\u0630" +
                    "\0\u065c\0\u0688\0\54\0\54\0\334\0\334\0\u06b4\0\334" +
                    "\0\u06e0\0\334\0\u070c\0\u0738\0\u03f4\0\u0764\0\334\0\u0630" +
                    "\0\334";

    private static int[] zzUnpackRowMap() {
        int[] result = new int[73];
        int offset = 0;
        offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackRowMap(String packed, int offset, int[] result) {
        int i = 0;  /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int high = packed.charAt(i++) << 16;
            result[j++] = high | packed.charAt(i++);
        }
        return j;
    }

    /**
     * The transition table of the DFA
     */
    private static final int[] ZZ_TRANS = zzUnpackTrans();

    private static final String ZZ_TRANS_PACKED_0 =
            "\1\2\1\3\1\4\1\5\1\6\2\7\1\10\1\7" +
                    "\2\11\1\7\1\12\1\13\1\7\1\2\1\14\1\15" +
                    "\1\16\1\17\1\20\1\21\1\2\1\22\1\23\1\24" +
                    "\1\25\1\26\2\7\1\27\1\30\1\31\1\7\1\32" +
                    "\1\33\1\34\1\35\1\36\1\7\1\37\1\40\2\7" +
                    "\56\0\1\4\54\0\1\41\1\42\20\0\1\41\26\0" +
                    "\1\42\1\43\1\44\1\42\13\6\10\42\13\6\1\42" +
                    "\1\6\3\42\1\6\1\42\3\6\4\0\13\7\10\0" +
                    "\13\7\1\0\1\7\3\0\1\7\1\0\3\7\4\0" +
                    "\4\7\1\45\6\7\1\46\7\0\13\7\1\0\1\7" +
                    "\3\0\1\7\1\0\3\7\4\0\5\7\2\11\1\47" +
                    "\1\7\1\50\1\7\10\0\13\7\1\0\1\7\3\0" +
                    "\1\7\1\0\3\7\4\0\5\7\1\51\1\52\4\7" +
                    "\10\0\13\7\1\0\1\7\3\0\1\7\1\0\3\7" +
                    "\4\0\5\7\2\50\4\7\10\0\13\7\1\0\1\7" +
                    "\3\0\1\7\1\0\3\7\17\14\1\53\1\54\33\14" +
                    "\3\0\1\41\1\42\20\0\1\41\1\55\31\0\13\7" +
                    "\10\0\2\7\1\56\10\7\1\0\1\7\3\0\1\7" +
                    "\1\0\3\7\4\0\13\7\10\0\7\7\1\57\3\7" +
                    "\1\0\1\7\3\0\1\7\1\0\3\7\4\0\7\7" +
                    "\1\60\3\7\10\0\13\7\1\0\1\7\3\0\1\7" +
                    "\1\0\3\7\4\0\13\7\10\0\5\7\1\61\5\7" +
                    "\1\0\1\7\3\0\1\7\1\0\3\7\4\0\13\7" +
                    "\10\0\1\7\1\62\11\7\1\0\1\7\3\0\1\7" +
                    "\1\0\3\7\4\0\7\7\1\63\3\7\10\0\6\7" +
                    "\1\64\4\7\1\0\1\7\3\0\1\7\1\0\3\7" +
                    "\4\0\13\7\10\0\2\7\1\65\10\7\1\0\1\7" +
                    "\3\0\1\7\1\0\3\7\47\0\1\66\10\0\13\7" +
                    "\10\0\13\7\1\0\1\7\3\0\1\7\1\0\1\7" +
                    "\1\67\1\7\1\42\1\43\1\44\51\42\2\0\1\44" +
                    "\51\0\4\70\1\45\1\71\2\45\1\72\6\45\10\70" +
                    "\13\45\1\70\1\45\3\70\1\45\1\70\3\45\4\0" +
                    "\13\73\10\0\13\73\1\0\1\73\3\0\1\73\1\0" +
                    "\3\73\4\0\5\7\2\51\1\7\1\51\2\7\10\0" +
                    "\13\7\1\0\1\7\3\0\1\7\1\0\3\7\4\0" +
                    "\5\7\2\50\1\47\3\7\10\0\13\7\1\0\1\7" +
                    "\3\0\1\7\1\0\3\7\4\0\5\7\2\51\4\7" +
                    "\10\0\13\7\1\0\1\7\3\0\1\7\1\0\3\7" +
                    "\1\14\2\0\51\14\25\0\1\74\32\0\13\7\10\0" +
                    "\3\7\1\75\7\7\1\0\1\7\3\0\1\7\1\0" +
                    "\3\7\4\0\13\7\10\0\1\76\12\7\1\0\1\7" +
                    "\3\0\1\7\1\0\3\7\4\0\13\7\10\0\6\7" +
                    "\1\77\4\7\1\0\1\7\3\0\1\7\1\0\3\7" +
                    "\4\0\13\7\10\0\7\7\1\100\3\7\1\0\1\7" +
                    "\3\0\1\7\1\0\3\7\4\0\13\7\10\0\1\101" +
                    "\12\7\1\0\1\7\3\0\1\7\1\0\3\7\4\0" +
                    "\13\7\10\0\13\7\1\0\1\7\3\0\1\7\1\0" +
                    "\2\7\1\102\5\70\1\103\2\70\1\104\47\70\1\45" +
                    "\1\71\1\7\10\45\10\70\13\45\1\70\1\45\3\70" +
                    "\1\45\1\70\3\45\4\70\1\45\1\71\1\45\1\105" +
                    "\1\72\6\45\10\70\13\45\1\70\1\45\3\70\1\45" +
                    "\1\70\3\45\4\0\13\7\10\0\1\106\12\7\1\0" +
                    "\1\7\3\0\1\7\1\0\3\7\4\0\13\7\10\0" +
                    "\12\7\1\107\1\0\1\7\3\0\1\7\1\0\3\7" +
                    "\5\70\1\103\1\0\52\70\1\103\1\70\1\110\1\104" +
                    "\43\70\4\0\7\7\1\111\3\7\10\0\13\7\1\0" +
                    "\1\7\3\0\1\7\1\0\3\7";

    private static int[] zzUnpackTrans() {
        int[] result = new int[1936];
        int offset = 0;
        offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackTrans(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            value--;
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }


    /* error codes */
    private static final int ZZ_UNKNOWN_ERROR = 0;
    private static final int ZZ_NO_MATCH = 1;
    private static final int ZZ_PUSHBACK_2BIG = 2;
    private static final char[] EMPTY_BUFFER = new char[0];
    private static final int YYEOF = -1;
    private static java.io.Reader zzReader = null; // Fake

    /* error messages for the codes above */
    private static final String ZZ_ERROR_MSG[] = {
            "Unkown internal scanner error",
            "Error: could not match input",
            "Error: pushback value was too large"
    };

    /**
     * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
     */
    private static final int[] ZZ_ATTRIBUTE = zzUnpackAttribute();

    private static final String ZZ_ATTRIBUTE_PACKED_0 =
            "\1\1\1\11\1\1\1\11\10\1\4\11\11\1\1\11" +
                    "\1\1\2\11\1\1\1\11\1\1\2\0\1\1\1\11" +
                    "\1\1\1\0\5\1\1\11\1\0\10\1\1\11\1\1" +
                    "\1\0\2\1\2\11\6\1\2\0\5\1";

    private static int[] zzUnpackAttribute() {
        int[] result = new int[73];
        int offset = 0;
        offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAttribute(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }

    /**
     * the current state of the DFA
     */
    private int zzState;

    /**
     * the current lexical state
     */
    private int zzLexicalState = YYINITIAL;

    /**
     * this buffer contains the current text to be matched and is
     * the source of the yytext() string
     */
    private CharSequence zzBuffer = "";

    /**
     * this buffer may contains the current text array to be matched when it is cheap to acquire it
     */
    private char[] zzBufferArray;

    /**
     * the textposition at the last accepting state
     */
    private int zzMarkedPos;

    /**
     * the textposition at the last state to be included in yytext
     */
    private int zzPushbackPos;

    /**
     * the current text position in the buffer
     */
    private int zzCurrentPos;

    /**
     * startRead marks the beginning of the yytext() string in the buffer
     */
    private int zzStartRead;

    /**
     * endRead marks the last character in the buffer, that has been read
     * from input
     */
    private int zzEndRead;

    /**
     * zzAtBOL == true <=> the scanner is currently at the beginning of a line
     */
    private boolean zzAtBOL = true;

    /**
     * zzAtEOF == true <=> the scanner is at the EOF
     */
    private boolean zzAtEOF;

    /* user code: */
    StringBuffer string = new StringBuffer();


    public _ArcLexer(java.io.Reader in) {
        this.zzReader = in;
    }

    /**
     * Creates a new scanner.
     * There is also java.io.Reader version of this constructor.
     *
     * @param in the java.io.Inputstream to read input from.
     */
    public _ArcLexer(java.io.InputStream in) {
        this(new java.io.InputStreamReader(in));
    }

    /**
     * Unpacks the compressed character translation table.
     *
     * @param packed the packed character translation table
     * @return the unpacked character translation table
     */
    private static char[] zzUnpackCMap(String packed) {
        char[] map = new char[0x10000];
        int i = 0;  /* index in packed string  */
        int j = 0;  /* index in unpacked array */
        while (i < 168) {
            int count = packed.charAt(i++);
            char value = packed.charAt(i++);
            do map[j++] = value; while (--count > 0);
        }
        return map;
    }

    public final int getTokenStart() {
        return zzStartRead;
    }

    public final int getTokenEnd() {
        return getTokenStart() + yylength();
    }

    public void reset(CharSequence buffer, int start, int end, int initialState) {
        zzBuffer = buffer;
        zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
        zzCurrentPos = zzMarkedPos = zzStartRead = start;
        zzPushbackPos = 0;
        zzAtEOF = false;
        zzAtBOL = true;
        zzEndRead = end;
        yybegin(initialState);
    }

    // For Demetra compatibility
    public void reset(CharSequence buffer, int initialState) {
        zzBuffer = buffer;
        zzBufferArray = null;
        zzCurrentPos = zzMarkedPos = zzStartRead = 0;
        zzPushbackPos = 0;
        zzAtEOF = false;
        zzAtBOL = true;
        zzEndRead = buffer.length();
        yybegin(initialState);
    }

    /**
     * Refills the input buffer.
     *
     * @return <code>false</code>, iff there was new input.
     * @throws java.io.IOException if any I/O-Error occurs
     */
    private boolean zzRefill() throws java.io.IOException {
        return true;
    }


    /**
     * Returns the current lexical state.
     */
    public final int yystate() {
        return zzLexicalState;
    }


    /**
     * Enters a new lexical state
     *
     * @param newState the new lexical state
     */
    public final void yybegin(int newState) {
        zzLexicalState = newState;
    }


    /**
     * Returns the text matched by the current regular expression.
     */
    public final CharSequence yytext() {
        return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
    }


    /**
     * Returns the character at position <tt>pos</tt> from the
     * matched text.
     * <p/>
     * It is equivalent to yytext().charAt(pos), but faster
     *
     * @param pos the position of the character to fetch.
     *            A value from 0 to yylength()-1.
     * @return the character at position pos
     */
    public final char yycharat(int pos) {
        return zzBufferArray != null ? zzBufferArray[zzStartRead + pos] : zzBuffer.charAt(zzStartRead + pos);
    }


    /**
     * Returns the length of the matched text region.
     */
    public final int yylength() {
        return zzMarkedPos - zzStartRead;
    }


    /**
     * Reports an error that occured while scanning.
     * <p/>
     * In a wellformed scanner (no or only correct usage of
     * yypushback(int) and a match-all fallback rule) this method
     * will only be called with things that "Can't Possibly Happen".
     * If this method is called, something is seriously wrong
     * (e.g. a JFlex bug producing a faulty scanner etc.).
     * <p/>
     * Usual syntax/scanner level error handling should be done
     * in error fallback rules.
     *
     * @param errorCode the code of the errormessage to display
     */
    private void zzScanError(int errorCode) {
        String message;
        try {
            message = ZZ_ERROR_MSG[errorCode];
        }
        catch (ArrayIndexOutOfBoundsException e) {
            message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
        }

        throw new Error(message);
    }


    /**
     * Pushes the specified amount of characters back into the input stream.
     * <p/>
     * They will be read again by then next call of the scanning method
     *
     * @param number the number of characters to be read again.
     *               This number must not be greater than yylength()!
     */
    public void yypushback(int number) {
        if (number > yylength())
            zzScanError(ZZ_PUSHBACK_2BIG);

        zzMarkedPos -= number;
    }


    /**
     * Resumes scanning until the next regular expression is matched,
     * the end of input is encountered or an I/O-Error occurs.
     *
     * @return the next token
     * @throws java.io.IOException if any I/O-Error occurs
     */
    public IElementType advance() throws java.io.IOException {
        int zzInput;
        int zzAction;

        // cached fields:
        int zzCurrentPosL;
        int zzMarkedPosL;
        int zzEndReadL = zzEndRead;
        CharSequence zzBufferL = zzBuffer;
        char[] zzBufferArrayL = zzBufferArray;
        char[] zzCMapL = ZZ_CMAP;

        int[] zzTransL = ZZ_TRANS;
        int[] zzRowMapL = ZZ_ROWMAP;
        int[] zzAttrL = ZZ_ATTRIBUTE;

        while (true) {
            zzMarkedPosL = zzMarkedPos;

            zzAction = -1;

            zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

            zzState = zzLexicalState;


            zzForAction:
            {
                while (true) {

                    if (zzCurrentPosL < zzEndReadL)
                        zzInput = zzBufferL.charAt(zzCurrentPosL++);
                    else if (zzAtEOF) {
                        zzInput = YYEOF;
                        break zzForAction;
                    } else {
                        // store back cached positions
                        zzCurrentPos = zzCurrentPosL;
                        zzMarkedPos = zzMarkedPosL;
                        boolean eof = zzRefill();
                        // get translated positions and possibly new buffer
                        zzCurrentPosL = zzCurrentPos;
                        zzMarkedPosL = zzMarkedPos;
                        zzBufferL = zzBuffer;
                        zzEndReadL = zzEndRead;
                        if (eof) {
                            zzInput = YYEOF;
                            break zzForAction;
                        } else {
                            zzInput = zzBufferL.charAt(zzCurrentPosL++);
                        }
                    }
                    int zzNext = zzTransL[zzRowMapL[zzState] + zzCMapL[zzInput]];
                    if (zzNext == -1) break zzForAction;
                    zzState = zzNext;

                    int zzAttributes = zzAttrL[zzState];
                    if ((zzAttributes & 1) == 1) {
                        zzAction = zzState;
                        zzMarkedPosL = zzCurrentPosL;
                        if ((zzAttributes & 8) == 8) break zzForAction;
                    }

                }
            }

            // store back cached position
            zzMarkedPos = zzMarkedPosL;

            switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
                case 16: {
                    return COMMA;
                }
                case 32:
                    break;
                case 15: {
                    return QUOTE;
                }
                case 33:
                    break;
                case 22: {
                    return COMMA_AT;
                }
                case 34:
                    break;
                case 18: {
                    return LINE_COMMENT;
                }
                case 35:
                    break;
                case 23: {
                    return CHAR_LITERAL;
                }
                case 36:
                    break;
                case 19: {
                    return IF;
                }
                case 37:
                    break;
                case 2: {
                    return BAD_CHARACTER;
                }
                case 38:
                    break;
                case 7: {
                    return LEFT_PAREN;
                }
                case 39:
                    break;
                case 20: {
                    return FN;
                }
                case 40:
                    break;
                case 14: {
                    return BACKQUOTE;
                }
                case 41:
                    break;
                case 17: {
                    return COMPOSER;
                }
                case 42:
                    break;
                case 25: {
                    return NIL;
                }
                case 43:
                    break;
                case 9: {
                    return LEFT_SQUARE;
                }
                case 44:
                    break;
                case 31: {
                    return QUOTE_KEYWORD;
                }
                case 45:
                    break;
                case 8: {
                    return RIGHT_PAREN;
                }
                case 46:
                    break;
                case 6: {
                    return STRING_LITERAL;
                }
                case 47:
                    break;
                case 21: {
                    return DO;
                }
                case 48:
                    break;
                case 4: {
                    return NUMERIC_LITERAL;
                }
                case 49:
                    break;
                case 29: {
                    return BLOCK_COMMENT;
                }
                case 50:
                    break;
                case 26: {
                    return LET;
                }
                case 51:
                    break;
                case 1: {
                    return SYMBOL;
                }
                case 52:
                    break;
                case 27: {
                    return DEF;
                }
                case 53:
                    break;
                case 28: {
                    return MAC;
                }
                case 54:
                    break;
                case 13: {
                    return EQ;
                }
                case 55:
                    break;
                case 24: {
                    return UNDERSCORE;
                }
                case 56:
                    break;
                case 12: {
                    return TILDE;
                }
                case 57:
                    break;
                case 5: {
                    return DOT;
                }
                case 58:
                    break;
                case 30: {
                    return WITH;
                }
                case 59:
                    break;
                case 11: {
                    return TRUE;
                }
                case 60:
                    break;
                case 3: {
                    return WHITESPACE;
                }
                case 61:
                    break;
                case 10: {
                    return RIGHT_SQUARE;
                }
                case 62:
                    break;
                default:
                    if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
                        zzAtEOF = true;
                        return null;
                    } else {
                        zzScanError(ZZ_NO_MATCH);
                    }
            }
        }
    }


}
